name: torch
channels:
  - bioconda
  - pytorch
  - idr
  - ome
  - conda-forge
  - defaults
  - torch
dependencies:
  - cudatoolkit=10.2
  - python=3.8
  - scipy
  - pytest
  - tqdm
  - poetry
  - pandas
  - torchinfo
  - tensorboard
  - flake8
  - umap-learn
  - python
  - future
  - jupyter
  - absl-py
  - pip
  - torchvision
  - matplotlib
  - pyyaml
  - click
  - black
  - rope
  - autopep8
  - pytorch
  - torchvision
  - numpy
  - torchaudio
  - pytorch-lightning
  - scikit-image
  - pytorch-model-summary
  - pyro-ppl
  - scikit-learn
  - pandas
  - matplotlib
  - datashader
  - bokeh
  - holoviews 
  - colorcet 
  - idr-py
  - torchvision
  - cudatoolkit=10.2
  - pytorch
  - matplotlib
  - tensorboard
  - idr-py
  - pytorch-lightning
  - matplotlib
  - scikit-learn
  - gsutil
  - dask-image
  - gcsfs
  - imageio
  - pip 
  - pip:
    - -e .
    - nonechucks