[tool.poetry]
name = "bio_vae"
version = "0.1.1"
description = ""
authors = ["Craig <ctr26@ebi.ac.uk>"]

[tool.poetry.scripts]
bioimrep = "main:main"

[tool.poetry.dependencies]
python = "^3.9"
torchvision = "^0.13.1"
torch = "^1.12.1"
torchinfo = "^1.7.0"
matplotlib = "^3.5.3"
pytorch-lightning = "1.7.0"
pyro-ppl = "^1.8.2"
scikit-image = "^0.19.3"
iteround = "^1.0.4"
ipykernel = "^6.15.2"
nonechucks = "^0.4.2"
pythae = "^0.0.8"
pytest = "^7.0.1"
pandas = "^1.5.2"
numpy = "^1.23.5"
bokeh = "^2.4.0"
umap-learn = {extras = ["plot"], version = "^0.5.3"}
colorcet = "^3.0.1"
holoviews = "^1.15.2"
# idr-py = "^0.4.2"
llvmlite = "^0.39.1"
torchmetrics = "^0.11.0"
tensorboard = "^2.11.2"
albumentations = "^1.3.0"
timm = "^0.6.13"
pip = "^23.1.2"
jsonargparse = {extras = ["signatures"], version = "^4.21.0"}
hydra-core = "^1.3.2"
pyqt5 = "^5.15.9"
pytorch-lightning-bolts = "0.3.2"
lightning-bolts = "^0.6.0"
requests = "^2.30.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = {version = "^22.6.0", allow-prereleases = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
